### PR TITLE
Add SSRF and DoS vulnerabilities

### PR DESCRIPTION
**Pull request by gled02**
As we discussed before, this PR comes from splitting PR #357 into two pull requests (the other PR is #364).
The main goal is to add SSRF and DoS vulnerabilities based on the user cases defined before.

Modifications like making some methods private or adding the contributor's name, have been made. We didn't change our implementation.

### CODE REVIEW

**Comment by preetkaran20** [comment]
Hi @gled02 ,
can you please raise the PR against `ssrf_unmerged` branch. Why? so that we have your changes in our branches and we can merge them later.

**Comment by preetkaran20** [comment]
Hi @gled02 ,
can you please raise the PR against `ssrf_unmerged` branch. Why? so that we have your changes in our branches and we can merge them later.

**Comment by preetkaran20** [comment]
Thanks !!!

**Comment by gled02** [comment]
Hi @preetkaran20,

Thanks a lot for your comments. We are really happy to have been able to contribute to VulnerableApp and to help the improvement of this useful project. We are glad to have chosen VulnerableApp as an open source project, for our university project. We learned a lot from this project and from your suggestions. @NMV01 and I, we are happy to share ideas and thoughts in future.

Regards,

**Pull request merged**
