### PR TITLE
Added logos

### PR DESCRIPTION
**Pull request by devabhishekpal**
Added two versions of the logo - three coloured and three black and white.

### CODE REVIEW

**Comment by devabhishekpal** [comment]
Kindly check @preetkaran20 @hemantgs

**Comment by preetkaran20** [comment]
LGTM. one question i have is, How did you created these logos ?

thanks,
Karan

**Review by preetkaran20 — APPROVED** [review]

**Comment by preetkaran20** [comment]
@devabhishekpal also please tell me you linked in and twitter accounts, as i was looking to publicise. @hemantgs  what do you think ?

**Comment by devabhishekpal** [comment]
Thank you @preetkaran20, I dont have a twitter currently. 
But this is my [LinkedIn](https://www.linkedin.com/in/abhishekpal2001/) profile 😃

**Comment by preetkaran20** [comment]
@devabhishekpal How did you created these logos ?

**Comment by devabhishekpal** [comment]
I used Adobe Illustrator to make these @preetkaran20

**Comment by preetkaran20** [comment]
> I used Adobe Illustrator to make these @preetkaran20
@devabhishekpal 
does adobe illustrator has some format which can be imported again to do some small modifications ? As these logo's are PNG so if we again use adobe illustrator PNG's might not be very useful

**Comment by devabhishekpal** [comment]
Yes it does. Shall I give it as SVG too?
@preetkaran20

**Comment by preetkaran20** [comment]
> Yes it does. Shall I give it as SVG too?
> @preetkaran20


If it has some format, lets checkin that format too as that format we can use to do minor modifications in future.

**Comment by devabhishekpal** [comment]
Okayyy then I am adding the SVG format too @preetkaran20

**Comment by preetkaran20** [comment]
> SVG

i think Encapsulated PostScript (EPS) is the format. Please check once.

**Comment by devabhishekpal** [comment]
Okay
I am adding EPS too
@preetkaran20

**Comment by devabhishekpal** [comment]
I added both EPS and SVG formats so that in the future you could use any Vector Editor to make changes to the file @preetkaran20

**Comment by preetkaran20** [comment]
Great work @devabhishekpal

**Comment by devabhishekpal** [comment]
Thank you @preetkaran20

**Pull request merged**
